### ISSUE TITLE
 movements smooth

### ISSUE THREAD

**Issue by egenial** [JeremyHeleine/Photo-Sphere-Viewer#10]
When I open google chrome the examples/example.html and interact with the photo movements are a little crazy, it is not as smooth as this example here.

http://kennydude.github.io/photosphere/test.html

No way to improve to become more gentle movements with the mouse?

**Comment by JeremyHeleine** [comment]
Hi,

You can play with the options `long_offset` and `lat_offset` which control the longitude and latitude to travel per pixel moved with the mouse (or by touch). Is that what you were searching for?

Jérémy

**Comment by egenial** [comment]
Hi Jeremy,

Can you give me an example of how to implement this?

**Comment by JeremyHeleine** [comment]
Hi,

Please find a concrete example of use in the `example1.js` file, in the `loadPredefinedPanorama()` function where the speed is divided by two (compared to the default values). Currently, only radians are supported, but I'll add the support for degrees later.

Don't hesitate if you have any question.

Jérémy
