### ISSUE TITLE
"Load the predefined panorama" doesn't work on the test.html

### ISSUE THREAD

**Issue by sebastiankempa** [JeremyHeleine/Photo-Sphere-Viewer#15]
Hi,
"Load the predefined panorama" doesn't work on the test.html

Regards, Sebastian

**Comment by JeremyHeleine** [comment]
Hi,

It works for me with Firefox. Which browser do you use? Do you have any error?

**Comment by sebastiankempa** [comment]
Hi, i tested on Mac, Google Chrome and Safari.
Upload Picture works fine but, predefined panorama will not work.

**Comment by sebastiankempa** [comment]
On Mac Firefox works fine.

**Comment by sebastiankempa** [comment]
Look Screenshot
![bildschirmfoto von safari 21-11-15 19-11-54](https://cloud.githubusercontent.com/assets/3936311/11319799/ce339946-9083-11e5-9b40-03ae570fe98f.jpg)

**Comment by sebastiankempa** [comment]
Look Screenshot - Error Google Chrome

![bildschirmfoto von google chrome 21-11-15 19-14-16](https://cloud.githubusercontent.com/assets/3936311/11319811/2d5f383a-9084-11e5-9a69-69e2198958cf.jpg)

**Comment by JeremyHeleine** [comment]
It seems that Chrome doesn't want to load the panorama when you're reading a local file. Just tested and, in fact, when accessing the file with `file:///path/to/the/file`, it doesn't work. However, if we load the file with a web server, it works fine.
I don't think there's anything we can do to fix this bug, as it's not really a bug.

**Comment by sebastiankempa** [comment]
Yes you are right. I've just tried on the server and it runs. Thank you and sorry for the false alarm. tanks
