### ISSUE TITLE
Default fov & default position

### ISSUE THREAD

**Issue by mistic100** [JeremyHeleine/Photo-Sphere-Viewer#2]
Would be cool to have a `default_fov`, `default_lat` and `default_long`.

I tried to call the `zoom` method but it didn't work because the camera was not initialized yet (I didn't found an `onReady` callback or similar)

And the `move` method is not public (and would have the same problem as `zoom` anyway)

Thank you

**Comment by JeremyHeleine** [comment]
Hi!

Good idea, I'll add these options in the next version.

The `zoom()` method is public (it is called by the navigation bar to zoom with the cursor) so you should be able to use it. But you're right, an `onReady` callback is missing. I'll add it.

Thanks for your feedback!

**Comment by mistic100** [comment]
The other thing I am missing is the `resize` method, I need to have it public to resize the viewer depending on page layout changes

BTW I am making a plugin for Piwigo photo gallery

**Comment by JeremyHeleine** [comment]
In fact `resize()` should be public, that's a good idea.
In a future version other methods will be public (and a true documentation will be there…), but I don't want all methods to be public. I think it is useless, as a lot of function are actually here to be used only once (they are just used to organize the code).
