### ISSUE TITLE
is it possible to rotate it manually say i want it to rotate {x:5,y:1}, so i can use pointer lock or arrow keys to rotate

### ISSUE THREAD

**Issue by techsin** [JeremyHeleine/Photo-Sphere-Viewer#27]
deg, radians, px, anything?

**Comment by techsin** [comment]
deg, radians, px, anything?

**Comment by JeremyHeleine** [comment]
Hi,

I plan to add the support of arrow keys in the future. In the meantime, it's possible to create the feature you want, but not so easily.

There isn't a method to directly rotate the panorama. It's a good idea, so I'll implement such a method.

Right now you can retrieve the current position with the `getPosition()` method. It returns an object containing two properties: `longitude` filled with the current longitude, and `latitude` for the current latitude. These values are in radians. You can also retrieve degrees with `getPositionInDegrees()` (same properties).

Once you have these values you can modify them and change the current position in PSV with the method `moveTo()` which accepts two arguments: the longitude and the latitude to show (in radians if you indicate numbers or in degrees if you indicate strings like `'42deg'`).

**Comment by techsin** [comment]
sorry forgot to do follow up but i was able to do it the way you just said.

http://s.codepen.io/techsin/debug/MymvVq

    function moveSphere(e) {
      var mx = (e.movementX || 0) / 1000 ;
      var my = (e.movementY || 0) / 1000 ;
      var old = psv.getPosition();
      psv.moveTo(old.longitude+mx, old.latitude+my);
}`

**Comment by JeremyHeleine** [comment]
Hi,

The latest update added the method you wanted. For example you can replace the two last lines of your code sample above with `psv.rotate(mx, my);`.

**Comment by techsin** [comment]
cool thanks
