### ISSUE TITLE
Keyboard navigation issues

### ISSUE THREAD

**Issue by mistic100** [JeremyHeleine/Photo-Sphere-Viewer#32]
Hello Jeremy. 
I tried to implement the keyboard navigation in my fork and discovered that it's not simple as you implemented it.

On Firefox and some versions of Chrome, KeyboardEvent.key does not exist, instead it's "code", or "char", or "keyCode", or "charCode", or "which".
See https://developer.mozilla.org/en-US/docs/Web/Events/keydown (it's the most inconsistent event I ever encountered).

Despite the fact it is deprecated the most reliable way is `evt.keyCode || evt.which` with

ArrowLeft = 37
ArrowUp = 38
Arrowright = 39
ArrowDown = 40

Or if you want to be clean, try `evt.key`  and fallback to numerical codes if it fails.

**Comment by mistic100** [comment]
Here is my temporary implementation (hardcoded deltas) :

```js
PhotoSphereViewer.KEYMAP = {
  33: 'PageUp',
  34: 'PageDown',
  37: 'ArrowLeft',
  38: 'ArrowUp',
  39: 'ArrowRight',
  40: 'ArrowDown',
  107: '+',
  109: '-'
};

PhotoSphereViewer.prototype._onKeyDown = function(evt) {
  var dLong = 0;
  var dLat = 0;
  var dZoom = 0;

  var key = evt.key || PhotoSphereViewer.KEYMAP[evt.keyCode || evt.which];

  switch (key) {
    case 'ArrowUp': dLat = 0.1; break;
    case 'ArrowDown': dLat = -0.1; break;
    case 'ArrowRight': dLong = 0.1; break;
    case 'ArrowLeft': dLong = -0.1; break;
    case 'PageUp':case '+': dZoom = 1; break;
    case 'PageDown':case '-': dZoom = -1; break;
  }

  if (dZoom !== 0) {
    this.zoom(this.prop.zoom_lvl + dZoom);
  }
  else if (dLat !== 0 || dLong !== 0) {
    this.rotate({
      longitude: this.prop.longitude + dLong,
      latitude: this.prop.latitude + dLat
    });
  }
};
```

**Comment by JeremyHeleine** [comment]
Hi,
Which version of Firefox do you use? On Firefox 44, `KeyboardEvent.key` does exist. However, you're right, I should also use the old APIs so I'll add fallbacks. Thanks for the suggestion!

**Comment by mistic100** [comment]
Strange because the bug is not resolved https://bugzilla.mozilla.org/show_bug.cgi?id=680830
(I was actually on Chrome on Fedora which way not be totally up to date)

**Comment by JeremyHeleine** [comment]
Finally had time to fix the issue. I also added a test in the `key` case: it seems that Edge supports `evt.key` but only indicates `Up` instead of `ArrowUp`, and so on.
