### ISSUE TITLE
Skewed view using panorama from Street View

### ISSUE THREAD

**Issue by ner00** [JeremyHeleine/Photo-Sphere-Viewer#39]
I've recently created a script to grab and stitch together Street View panoramas into single JPGs.
I've tested a few of them and all have a slight skew, more noticeable in certain longitudes/latitudes than others. 

I tried changing a few parameters in PSV but wasn't able to get any satisfactory results. I'm wondering what is so special about Street View panoramas that makes them visually skewed and if it is possible to adjust PSV settings to fix their usage in it.

I'll leave here two panoramas as examples and respective print-screens to demonstrate what I'm trying to say.

**Fontevraud Abbey**
- Street View URL: [#loire-castles-france/fontevraud-royal-abbey](https://www.google.com/streetview/#loire-castles-france/fontevraud-royal-abbey)
- Panorama image: [http://i.imgur.com/JFxqXzN.jpg](http://i.imgur.com/JFxqXzN.jpg)
- Street View print-screen: [http://i.imgur.com/PhQX6sb.jpg](http://i.imgur.com/PhQX6sb.jpg)
- PS Viewer print-screen: [http://i.imgur.com/zL6A7sM.jpg](http://i.imgur.com/zL6A7sM.jpg)

**Milford Track**
- Street View URL: [#great-walks-of-new-zealand/view-of-milford-sound-milford-track](https://www.google.com/streetview/#great-walks-of-new-zealand/view-of-milford-sound-milford-track)
- Panorama image: [http://i.imgur.com/xiOwWfW.jpg](http://i.imgur.com/xiOwWfW.jpg)
- Street View print-screen: [http://i.imgur.com/myzXn3K.jpg](http://i.imgur.com/myzXn3K.jpg)
- PS Viewer print-screen: [http://i.imgur.com/yRvCqai.jpg](http://i.imgur.com/yRvCqai.jpg)

Thanks for the help!

**Comment by JeremyHeleine** [comment]
Wow, pretty weird. I never saw this bug before but obviously it shouldn't appear. As a workaround, it could be possible to provide an option to rotate the sphere on which the panorama is applied, but it's not really a very good solution.

**Comment by ner00** [comment]
As a correction to my last statement, this problem doesn't happen with all Street View panoramas, it just felt that way at the time given the small amount of samples I had tried. But it is common enough for Google to have created some sort of algorithm to adjust for this since their viewer shows the exact same panorama with no noticeable distortion angle. 

The workaround you mention is not ideal but I don't really think there's anything better you could do short of creating an algorithm that detects the horizon and adjusts for it. I don't know, I've just dabbled in panoramas for a few weeks. Still, something that can correct this would be very nice.
