### ISSUE TITLE
Wavy panorama aberration/distortion

### ISSUE THREAD

**Issue by ner00** [JeremyHeleine/Photo-Sphere-Viewer#40]
I recently took on a few cubic panoramas and converted them to equirectangular versions.
Initially I thought something was messed up with my conversion method (cubic2erect) but after a close look it became apparent that it was Photo Sphere Viewer that was distorting the panorama.

I never noticed this in any other panorama and don't know if it is apparent because of the geometric shapes present in the panorama I tried it with but the fact remains that only PSViewer will distort the panorama, none of the other 2 viewers I tested it with gave this issue.

Here is the example:
* [Original cubic panorama](http://i.imgur.com/FuRyEt2.jpg)
* [Converted equirectangular panorama](http://i.imgur.com/RchwAEc.jpg)
* [View1- PSViewer](http://i.imgur.com/XovhWpP.jpg)
* [View1- FPSViewer](http://i.imgur.com/MXbvPLO.jpg)
* [View2- PSViewer](http://i.imgur.com/tu0TMGH.jpg)
* [View2- Pannellum](http://i.imgur.com/jG0KHRt.jpg)

* [Live Pannellum demo using converted panorama](https://cdn.pannellum.org/2.2/pannellum.htm?panorama=https://i.imgur.com/RchwAEc.jpg&autoLoad=true&autoRotate=1&hfov=120&pitch=-30)

Pretty weird... not sure why this is the case.

**Comment by JeremyHeleine** [comment]
Hi,

It's a known issue (see [#18](https://github.com/JeremyHeleine/Photo-Sphere-Viewer/issues/18)). It happens during the rendering. I have an idea of why it happens, but I don't know currently how to fix it, sadly.

**Comment by ner00** [comment]
Sorry that I didn't search for this in existing issues.
Well, I hope that some day you are able to fix this.

Thanks nonetheless.
