### ISSUE TITLE
VR feature not compatible with latest Three.js

### ISSUE THREAD

**Issue by AdrienPoupa** [JeremyHeleine/Photo-Sphere-Viewer#48]
Hi,

I've tried the VR feature (cardboard icon), it does not work with Three.js v82. However, no problem with the version provided here (v71).

When I click on the icon, nothing happens. It is hard to debug since I cannot get the icon to show in my desktop browser.

**Comment by JeremyHeleine** [comment]
Hi,

That's the problem when using external libraries… and that's why I must finish my own renderer!

I'll try to fix the issue, anyway, as it's important to stay up-to-date. Thanks for reporting the issue.
