### ISSUE TITLE
Create a helper to change picture easily

### ISSUE THREAD

**Issue by AdrienPoupa** [JeremyHeleine/Photo-Sphere-Viewer#49]
Can you create a helper similar to what mistic100 did in his fork?

So you can simply call to setPanorama to change picture.

```
.setPanorama(path [, position] [, transition]) -> Promise

Loads a new panorama image, optionnally changing the camera position and activating or not the transition animation.

viewer.setPanorama(
  'panorama-2.jpg',
  {
    longitude: Math.PI,
    latitude: 0
  },
  true
);
```

http://photo-sphere-viewer.js.org/

**Comment by JeremyHeleine** [comment]
Hi,

It's a feature already planned. Just need some time to implement it, along other features.

**Comment by AdrienPoupa** [comment]
That's good to hear! Let me know if I may be of any help.
