### ISSUE TITLE
example.html stuck on "Loading..."

### ISSUE THREAD

**Issue by osmotischen** [JeremyHeleine/Photo-Sphere-Viewer#5]
The "choose file" viewer works in example1.html but when I try to open example.html I'm greeted "Loading..." which does not go away.

It works fine on firefox but not on chrome. I tested on two separate computers with extensions disabled.

**Comment by JeremyHeleine** [comment]
It works fine for me. Which version of Chrome do you use (that way I can try to test in the same conditions to see what's wrong)?

**Comment by osmotischen** [comment]
42.0.2311.135 m

This is what my chrome://version page shows: https://i.imgur.com/WDwC0F9.png

**Comment by osmotischen** [comment]
After some more testing it seems to work when the files are hosted on a site but not when on a local directory. The same problem happens with some other photo-sphere viewers, so it's probably an issue with Chrome.
