### ISSUE TITLE
Too many active WebGL contexts. Oldest context will be lost.

### ISSUE THREAD

**Issue by jeremiecourlivant** [JeremyHeleine/Photo-Sphere-Viewer#52]
Hello,

Your library works very well and on my website, some pages are 11 panoramas at the same time without issues.

But, today, I would like to put 19 images on the same page. In this case, there are three warnings like this:  

`three.min.js:627 WARNING: Too many active WebGL contexts. Oldest context will be lost.`

Three images, not always the sames, don't work and display [this](https://goo.gl/photos/Ev3oRHZ5CjbPhPpC8) . The other panoramas work.

The warning is in three.min.js but in your library, can you make something to avoid this problem ? Or can I make something when you call a PhotoSphereViewer to avoid this problem ?

Thanks,
Jérémie

**Comment by JeremyHeleine** [comment]
Hi,

As you said, the issue concerns Three.js (and even WebGL if I understand well), and there's nothing I can do (I think). I think it's a kind of security from WebGL, to prevent the memory to be entirely filled.

**Comment by jeremiecourlivant** [comment]
Ok, thank you for your response, I find another way, like miniatures to have only one viewer per page.
