### ISSUE TITLE
Is it possible to multiple images  

### ISSUE THREAD

**Issue by siddiknmh** [JeremyHeleine/Photo-Sphere-Viewer#56]
Can I use the script with multiple images  in one page ?

**Comment by JeremyHeleine** [comment]
Hi,

Depending on the exact meaning of your question: yes, and no.

You can add several PSV containers with one panorama per container. All panoramas can be run simultaneously without any problem. The only limit is the device used to access the page.

If you want to add several panorama into only one PSV object, it's not possible for the moment. I plan to add the feature, but it's not possible for the moment.

**Comment by eliasfaical** [comment]
So I need to create two DIVs?

`<div id = "photosphere-1"> </ div>
<div id = "photosphere-2"> </ div>`

And call the function twice?

`Let PSV = new PhotoSphereViewer ({})`

**Comment by JeremyHeleine** [comment]
Yes, with the right ID in each call, of course.

**Comment by eliasfaical** [comment]
Yes, it worked. Thanks!

**Comment by soravgarg123** [comment]
I am using multiple div, working fine with multiple images. but I am trying to add a marker and in that case, it showing a marker on the last image, when I try to click on the first image to add a marker, then its showing marker image on the last image, what is the solution?
