### ISSUE TITLE
Are there plans to add street view like moving options, so user can move around?

### ISSUE THREAD

**Issue by techsin** [JeremyHeleine/Photo-Sphere-Viewer#57]
basically every paranoma would have links to another paranoma to which arrow would be pointing. If you give each paranoma x,y location then arrows can easily be directed in right direction. x,y could lang, long. 

arrows are basically another layer of controls hover little below camera point.

**Comment by JeremyHeleine** [comment]
Hi,

Yes, I plan to implement such a feature. I just want to add other things before.

**Comment by techsin** [comment]
is there a way to know what are your plans, like trello board etc.. this way people could help too.

**Comment by JeremyHeleine** [comment]
Not for the moment. I keep ideas of features to implement on my computer so it's private. I think I'll create a Trello board in the future, it could be a good idea.

**Comment by techsin** [comment]
definitely was thinking the same thinking.
