### ISSUE TITLE
Cube Image Load error not thrown

### ISSUE THREAD

**Issue by littlevahn** [JeremyHeleine/Photo-Sphere-Viewer#66]
Im running into an error when trying to load a cube type image. When one of the images in the array passed in is broken or is a 404 the error generated by the code is never fully thrown out to the constructor. So catching this error becomes very hard. Also when this happens you can not instantiate a new instance of the viewer. Im guessing there is something with the loader class that is keeping this from happening. Says its still trying to load the other image. Even though it has already error'd. 

Let me know if you need more details.

This is the line where the original error is being thrown but goes no where: (from minified version)
throw this.container.textContent = "Cannot load image", d.reject(b), new v("Cannot load image " + a)

**Comment by JeremyHeleine** [comment]
Hi,

There is no such a line in the code of Photo Sphere Viewer. If you are talking about a fork of PSV, I suggest you to contact its author instead of me.

**Comment by littlevahn** [comment]
Its a download from here: http://photo-sphere-viewer.js.org/ Is the code in here a forked version? Ah, it is, saw your name at the top, confused me. Thanks and sorry.
