### ISSUE TITLE
Dynamic loading photo by block 

### ISSUE THREAD

**Issue by sparksofire** [JeremyHeleine/Photo-Sphere-Viewer#67]
I have a so big photo(about 20MB). May I dynamic loading it by block instead of loading the whole image when the view is initialized?
I am very sorry for my poor English.

**Comment by sparksofire** [comment]
And may I load different resolutions for different zoom levels?

**Comment by JeremyHeleine** [comment]
Hi,

For now, it is not possible to give different parts of your panorama to PSV (but it's a feature I plan to implement). Also, it is not possible to give multiple images, even for the different zoom levels. However, it's a pretty good idea, I'll add it to the (very long) list of features to implement!

**Comment by sparksofire** [comment]
Thanks very much !!!! And can you give me some advice to achieve them(no need sphere panoramas )? I am so anxiously 😣😣 !!

**Comment by sparksofire** [comment]
I want to achieve that dynamic loading a big photo by block, load different resolutions for different zoom levels, can marker (no need sphere panoramas ). Sorry to disturb you.

**Comment by JeremyHeleine** [comment]
I'm sorry but I'm not sure to understand. These features are not available for now, and they ask for several changes in PSV's source code to be implemented properly.

**Comment by sparksofire** [comment]
I am sorry to my poor English, thanks very much!
