### ISSUE TITLE
stop auto rotate 

### ISSUE THREAD

**Issue by saravanasksp** [JeremyHeleine/Photo-Sphere-Viewer#73]
Here my script url 

[http://photo-sphere-viewer.js.org/dist/Photo-Sphere-Viewer/dist/photo-sphere-viewer.min.css](http://photo-sphere-viewer.js.org/dist/Photo-Sphere-Viewer/dist/photo-sphere-viewer.min.css)

**Comment by josueadelima** [comment]
@saravanasksp this is not an issue, also the link is for a css file..., if you want to stop autorotate you can just remove from the nabvar the autorotate button.
