### ISSUE TITLE
Pan glitch 

### ISSUE THREAD

**Issue by josueadelima** [JeremyHeleine/Photo-Sphere-Viewer#74]
Hi, im using Safari Versión 11.0 (13604.1.38.1.6) on macOS 10.13, when using the pan feature at some point the photo glitch or move position very quickly.

You can check a live example on the home page for this site: https://gifted-leakey-84686d.netlify.com or with this video: https://youtu.be/eeNigseV-mA

Thanks

**Comment by maxm199** [comment]
It's the h1 with width all the page, when the mouse goes over the h1 element which is over the pano image it stops from dragging the image.
