### ISSUE TITLE
Disable scrollwheel

### ISSUE THREAD

**Issue by VincentGarreau** [JeremyHeleine/Photo-Sphere-Viewer#9]
Hi @JeremyHeleine! Love this plugin, nice job! One feature request would be to add an option to control the scrollwheel only like Google Maps (boolean). Very useful for a grid of photo-sphere-viewers for example :)

Great work and thank you.

**Comment by JeremyHeleine** [comment]
Hi!

A grid of panoramas, wow! Considering the weight of one panorama file, just thinking about the amount of data to download is pretty crazy. But hey, why not after all. :P

Of course, there's no problem, I'll add this boolean (just not right now, I have some troubles with another project, but soon).

Thank you for your interest and your idea! :)

**Comment by VincentGarreau** [comment]
Great, thanks for your quick reply! :+1:

**Comment by JeremyHeleine** [comment]
Feature added in the latest version: you can set the option `allow_scroll_to_zoom` to `false`.
Thanks again for your idea!
