### ISSUE TITLE
VR viewer not working properly!

### ISSUE THREAD

**Issue by drashti2277** [JeremyHeleine/Photo-Sphere-Viewer#95]
Hi,  I want to enable VR view in my app and have added stereo  and gyroscope as navbar options. 
When I run it I get stereo icon but  it doesn't split image in two as expected. It does automatically activate gyroscope and full-screen and landscape orientation when clicked. 
I have included StereoEffect.js ,NoSleep.js, DeviceOrientationControls.js etc which are needed to make it work.  I've tried many ways but nothing is helping me. Please let me know if I'm missing something to enable VR view.
Here is my code :-
  var PSV = new PhotoSphereViewer({
        // main configuration
        panorama: 'image1.jpg',
        container: 'PSV',
        loading_img: 'img.gif',
        time_anim: false,
        navbar: [
        'stereo',
        'gyroscope',
        'fullscreen',
        'autorotate',
          'zoom',
          'caption',
          'download',
        ],
        caption: ' <b>CAPTION</b>',
        default_fov: 70,
        default_lat: 0.3,
        mousewheel: true,
        stereo:true,
        gyroscope:true,
        touchmove_two_fingers: true,
        size: {
          height: window.innerHeight,
          width: window.innerWidth
        }
      });

**Comment by kambleaa007** [comment]
whats update on closing issue
